
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: zeebeclients.zeebe.io.zeebe
spec:
  group: zeebe.io.zeebe
  names:
    kind: ZeebeClient
    listKind: ZeebeClientList
    plural: zeebeclients
    singular: zeebeclient
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ZeebeClient is the Schema for the zeebeclients API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ZeebeClientSpec defines the desired state of ZeebeClient
          properties:
            clientId:
              type: string
            clientName:
              type: string
            clusterId:
              type: string
            secretName:
              type: string
            zeebeClientDetails:
              properties:
                ZEEBE_ADDRESS:
                  type: string
                ZEEBE_AUTHORIZATION_SERVER_URL:
                  type: string
                ZEEBE_CLIENT_ID:
                  type: string
                name:
                  type: string
              required:
              - ZEEBE_ADDRESS
              - ZEEBE_AUTHORIZATION_SERVER_URL
              - ZEEBE_CLIENT_ID
              - name
              type: object
          required:
          - clientName
          - clusterId
          type: object
        status:
          description: ZeebeClientStatus defines the observed state of ZeebeClient
          properties:
            status:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
